const vscode = require("vscode");

/**
 * Builder Startup Extension
 *
 * Automatically configures the workspace layout for non-technical builders:
 * 1. Opens the Claude Code sidebar (AI assistant)
 * 2. Opens Simple Browser with a live preview of the running app
 *
 * The dev server is started separately by a VS Code task (runOn: folderOpen)
 * generated by entrypoint.sh.
 */

const PREVIEW_URL = "http://localhost:3100";
const STARTUP_DELAY_MS = 5000; // Wait for extensions + dev server to initialize

async function activate(context) {
  // Wait for other extensions and the dev server task to spin up
  await sleep(STARTUP_DELAY_MS);

  // 1. Open Claude Code in the sidebar
  await openClaudeSidebar();

  // 2. Open Simple Browser with the live preview
  await openSimpleBrowser(PREVIEW_URL);
}

async function openClaudeSidebar() {
  // Target the primary sidebar view container (the sparkle icon in the activity bar)
  const commands = [
    "workbench.view.extension.claude-sidebar",
    "claudeVSCodeSidebar.focus",
    "claude-vscode.sidebar.open",
  ];

  for (const cmd of commands) {
    try {
      await vscode.commands.executeCommand(cmd);
      return; // Success — stop trying
    } catch {
      // Command not available, try next
    }
  }
  console.warn("[builder-startup] Could not open Claude Code sidebar");
}

async function openSimpleBrowser(url) {
  // Try different Simple Browser command variants across code-server versions
  const commands = [
    { cmd: "simpleBrowser.api.open", args: [vscode.Uri.parse(url)] },
    { cmd: "simpleBrowser.show", args: [url] },
  ];

  for (const { cmd, args } of commands) {
    try {
      await vscode.commands.executeCommand(cmd, ...args);
      return;
    } catch {
      // Not available, try next
    }
  }
  console.warn("[builder-startup] Could not open Simple Browser");
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function deactivate() {}

module.exports = { activate, deactivate };
