const vscode = require("vscode");

/**
 * Builder Startup Extension
 *
 * Automatically configures the workspace layout for non-technical builders:
 * 1. Opens the Claude Code sidebar (primary — code-server doesn't support secondary)
 * 2. Opens the WELCOME.md guide as a regular editor file in the center
 *
 * The dev server is started separately by a VS Code task (runOn: folderOpen)
 * generated by entrypoint.sh.
 */

const WELCOME_FILE = "/home/coder/project/WELCOME.md";
const STARTUP_DELAY_MS = 5000;

async function activate(context) {
  await sleep(STARTUP_DELAY_MS);

  // 1. Open the welcome guide as a regular editor file (not a webview preview —
  //    markdown.showPreview causes deserialization crashes in code-server)
  await openWelcomePage();

  // 2. Open Claude Code in the primary sidebar
  //    (Claude Code sets doesNotSupportSecondarySidebar=true in code-server,
  //     so the real chat lives in the primary sidebar, not the secondary one)
  await openClaudeSidebar();
}

async function openClaudeSidebar() {
  const commands = [
    "workbench.view.extension.claude-sidebar",
    "claudeVSCodeSidebar.focus",
    // Fallbacks for secondary sidebar (if future code-server supports it)
    "workbench.view.extension.claude-sidebar-secondary",
    "claudeVSCodeSidebarSecondary.focus",
  ];

  for (const cmd of commands) {
    try {
      await vscode.commands.executeCommand(cmd);
      return;
    } catch {
      // Command not available, try next
    }
  }
  console.warn("[builder-startup] Could not open Claude Code sidebar");
}

async function openWelcomePage() {
  try {
    const uri = vscode.Uri.file(WELCOME_FILE);
    await vscode.window.showTextDocument(uri, {
      preview: true,
      preserveFocus: true, // Keep focus on the sidebar, not the editor
    });
  } catch {
    console.warn("[builder-startup] Could not open WELCOME.md");
  }
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function deactivate() {}

module.exports = { activate, deactivate };
